export const AUDIT_ENTITY_TYPES = {
  PROPERTY: 'PROPERTY',

  OWNERSHIP: 'OWNERSHIP',

  OWNERSHIP_TYPE: 'OWNERSHIP_TYPE',

  MAINTENANCE: 'MAINTENANCE',

  INCIDENT: 'INCIDENT',

  RETIREMENT: 'RETIREMENT',

  DISPOSAL: 'DISPOSAL',

  DISPOSAL_ITEM: 'DISPOSAL_ITEM',

  ASSET: 'ASSET',

  ASSET_ASSIGNMENT: 'ASSET_ASSIGNMENT',

  ASSET_MOVEMENT: 'ASSET_MOVEMENT',

  ASSET_LOCATION: 'ASSET_LOCATION',

  ACQUISITION: 'ACQUISITION',

  ACQUISITION_ITEM: 'ACQUISITION_ITEM',

  ACQUISITION_METHOD: 'ACQUISITION_METHOD',

  BUILDING: 'BUILDING',

  BUILDING_TYPE: 'BUILDING_TYPE',

  BUILDING_CONDITION: 'BUILDING_CONDITION',

  BUILDING_SPACE_TYPE: 'BUILDING_SPACE_TYPE',

  BUILDING_SPACE: 'BUILDING_SPACE',

  EMPLOYEE: 'EMPLOYEE',

  DOCUMENT: 'DOCUMENT',

  SYSTEM_SETTING: 'SYSTEM_SETTING',
} as const;

export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];

export const AUDIT_ACTIONS = {
  PROPERTY_CREATED: 'PROPERTY_CREATED',

  PROPERTY_UPDATED: 'PROPERTY_UPDATED',

  PROPERTY_DEACTIVATED: 'PROPERTY_DEACTIVATED',

  OWNERSHIP_CREATED: 'OWNERSHIP_CREATED',

  OWNERSHIP_UPDATED: 'OWNERSHIP_UPDATED',

  OWNERSHIP_DEACTIVATED: 'OWNERSHIP_DEACTIVATED',

  OWNERSHIP_TYPE_CREATED: 'OWNERSHIP_TYPE_CREATED',

  OWNERSHIP_TYPE_UPDATED: 'OWNERSHIP_TYPE_UPDATED',

  OWNERSHIP_TYPE_DEACTIVATED: 'OWNERSHIP_TYPE_DEACTIVATED',

  MAINTENANCE_CREATED: 'MAINTENANCE_CREATED',

  MAINTENANCE_UPDATED: 'MAINTENANCE_UPDATED',

  MAINTENANCE_REQUESTED: 'MAINTENANCE_REQUESTED',

  MAINTENANCE_ASSIGNED: 'MAINTENANCE_ASSIGNED',

  MAINTENANCE_APPROVED: 'MAINTENANCE_APPROVED',

  MAINTENANCE_STARTED: 'MAINTENANCE_STARTED',

  MAINTENANCE_COMPLETED: 'MAINTENANCE_COMPLETED',

  MAINTENANCE_CANCELLED: 'MAINTENANCE_CANCELLED',

  MAINTENANCE_SERVICE_CREATED: 'MAINTENANCE_SERVICE_CREATED',

  MAINTENANCE_SERVICE_UPDATED: 'MAINTENANCE_SERVICE_UPDATED',

  MAINTENANCE_SERVICE_DELETED: 'MAINTENANCE_SERVICE_DELETED',

  INCIDENT_CREATED: 'INCIDENT_CREATED',

  INCIDENT_UPDATED: 'INCIDENT_UPDATED',

  INCIDENT_REPORTED: 'INCIDENT_REPORTED',

  INCIDENT_ASSIGNED: 'INCIDENT_ASSIGNED',

  INCIDENT_STARTED: 'INCIDENT_STARTED',

  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',

  INCIDENT_CLOSED: 'INCIDENT_CLOSED',

  INCIDENT_CANCELLED: 'INCIDENT_CANCELLED',

  RETIREMENT_CREATED: 'RETIREMENT_CREATED',

  RETIREMENT_REQUESTED: 'RETIREMENT_REQUESTED',

  RETIREMENT_APPROVED: 'RETIREMENT_APPROVED',

  RETIREMENT_CANCELLED: 'RETIREMENT_CANCELLED',

  DISPOSAL_CREATED: 'DISPOSAL_CREATED',

  DISPOSAL_REQUESTED: 'DISPOSAL_REQUESTED',

  DISPOSAL_APPROVED: 'DISPOSAL_APPROVED',

  DISPOSAL_CANCELLED: 'DISPOSAL_CANCELLED',

  DISPOSAL_ITEM_CREATED: 'DISPOSAL_ITEM_CREATED',

  DISPOSAL_ITEM_UPDATED: 'DISPOSAL_ITEM_UPDATED',

  ASSET_CREATED: 'ASSET_CREATED',

  ASSET_UPDATED: 'ASSET_UPDATED',

  ASSET_ASSIGNED: 'ASSET_ASSIGNED',

  ASSET_RETURNED: 'ASSET_RETURNED',

  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',

  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',

  ASSET_MOVED: 'ASSET_MOVED',

  ASSET_LOCATION_CREATED: 'ASSET_LOCATION_CREATED',

  ASSET_LOCATION_UPDATED: 'ASSET_LOCATION_UPDATED',

  ASSET_LOCATION_DEACTIVATED: 'ASSET_LOCATION_DEACTIVATED',

  ACQUISITION_UPDATED: 'ACQUISITION_UPDATED',

  ACQUISITION_CREATED: 'ACQUISITION_CREATED',

  ACQUISITION_ITEM_CREATED: 'ACQUISITION_ITEM_CREATED',

  ACQUISITION_ITEM_UPDATED: 'ACQUISITION_ITEM_UPDATED',

  ACQUISITION_METHOD_CREATED: 'ACQUISITION_METHOD_CREATED',

  ACQUISITION_METHOD_UPDATED: 'ACQUISITION_METHOD_UPDATED',

  ACQUISITION_METHOD_DEACTIVATED: 'ACQUISITION_METHOD_DEACTIVATED',

  ACQUISITION_METHOD_ACTIVATED: 'ACQUISITION_METHOD_ACTIVATED',

  BUILDING_CREATED: 'BUILDING_CREATED',

  BUILDING_UPDATED: 'BUILDING_UPDATED',

  BUILDING_DEACTIVATED: 'BUILDING_DEACTIVATED',

  BUILDING_TYPE_CREATED: 'BUILDING_TYPE_CREATED',

  BUILDING_TYPE_UPDATED: 'BUILDING_TYPE_UPDATED',

  BUILDING_TYPE_DEACTIVATED: 'BUILDING_TYPE_DEACTIVATED',

  BUILDING_CONDITION_CREATED: 'BUILDING_CONDITION_CREATED',

  BUILDING_CONDITION_UPDATED: 'BUILDING_CONDITION_UPDATED',

  BUILDING_CONDITION_DEACTIVATED: 'BUILDING_CONDITION_DEACTIVATED',

  BUILDING_SPACE_TYPE_CREATED: 'BUILDING_SPACE_TYPE_CREATED',

  BUILDING_SPACE_TYPE_UPDATED: 'BUILDING_SPACE_TYPE_UPDATED',

  BUILDING_SPACE_TYPE_DEACTIVATED: 'BUILDING_SPACE_TYPE_DEACTIVATED',

  BUILDING_SPACE_CREATED: 'BUILDING_SPACE_CREATED',

  BUILDING_SPACE_UPDATED: 'BUILDING_SPACE_UPDATED',

  BUILDING_SPACE_DEACTIVATED: 'BUILDING_SPACE_DEACTIVATED',

  EMPLOYEE_DEACTIVATED: 'EMPLOYEE_DEACTIVATED',

  DOCUMENT_CREATED: 'DOCUMENT_CREATED',

  DOCUMENT_UPDATED: 'DOCUMENT_UPDATED',

  DOCUMENT_DELETED: 'DOCUMENT_DELETED',

  DOCUMENT_VERSION_CREATED: 'DOCUMENT_VERSION_CREATED',

  SYSTEM_SETTING_UPDATED: 'SYSTEM_SETTING_UPDATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export type AuditJsonValue =
  | string
  | number
  | boolean
  | null
  | AuditJsonValue[]
  | {
      [key: string]: AuditJsonValue;
    };

export type CreateAuditLogInput = {
  userId: string;

  action: AuditAction;

  entityType: AuditEntityType;

  entityId: string;

  description: string;

  oldValue?: AuditJsonValue;

  newValue?: AuditJsonValue;
};
